# Generated by Django 4.2.28 on 2026-02-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to='providers/profile/%Y/%m/%d'),
        ),
    ]
