# Generated by Django 4.2.28 on 2026-02-23 23:53

import re
from django.db import migrations

LOCATION_LABELS = {
    "makkah": "Makkah",
    "mecca": "Makkah",
    "madinah": "Madinah",
    "madina": "Madinah",
    "medina": "Madinah",
}
BLOCKED_BIO_TERMS = (
    "contact me privately",
    "contact me private",
    "contact me",
    "private contact",
    "call me",
    "dm me",
    "direct message",
    "whatsapp",
    "telegram",
    "snapchat",
    "email me",
    "outside the platform",
)
ALLOWED_CREDENTIAL_SUMMARY_FLAGS = {
    "UMRAH_BADAL_SUPPORT",
    "ZIYARAH_GUIDE_SUPPORT",
    "ELDERLY_FAMILY_SUPPORT",
    "MULTILINGUAL_ASSISTANCE",
    "ON_TIME_UPDATES",
}


def _resolve_location(value):
    text = str(value or "").strip().lower()
    return LOCATION_LABELS.get(text, "")


def sanitize_provider_profile_data(apps, schema_editor):
    ProviderProfile = apps.get_model("accounts", "ProviderProfile")

    for profile in ProviderProfile.objects.all():
        update_fields = []

        normalized_city = _resolve_location(profile.city)
        normalized_locations = []
        base_locations = profile.base_locations if isinstance(profile.base_locations, list) else []
        for value in base_locations:
            resolved = _resolve_location(value)
            if resolved:
                normalized_locations.append(resolved)
                break

        effective_city = normalized_city or (normalized_locations[0] if normalized_locations else "Makkah")
        effective_locations = [effective_city]

        if profile.city != effective_city:
            profile.city = effective_city
            update_fields.append("city")
        if profile.base_locations != effective_locations:
            profile.base_locations = effective_locations
            update_fields.append("base_locations")

        bio = str(profile.bio or "").strip()
        lowered = bio.lower()
        bio_has_private_content = (
            bool(re.search(r"\d", bio))
            or any(term in lowered for term in BLOCKED_BIO_TERMS)
            or "@" in bio
            or "http://" in lowered
            or "https://" in lowered
        )
        if bio_has_private_content and profile.bio != "":
            profile.bio = ""
            update_fields.append("bio")

        raw_flags = [item.strip() for item in str(profile.credentials_summary or "").split(",") if item.strip()]
        clean_flags = [flag for flag in raw_flags if flag in ALLOWED_CREDENTIAL_SUMMARY_FLAGS]
        deduped_flags = list(dict.fromkeys(clean_flags))
        normalized_credentials = ",".join(deduped_flags)
        if profile.credentials_summary != normalized_credentials:
            profile.credentials_summary = normalized_credentials
            update_fields.append("credentials_summary")

        if update_fields:
            profile.save(update_fields=update_fields)


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_providerprofile_profile_photo'),
    ]

    operations = [
        migrations.RunPython(sanitize_provider_profile_data, noop_reverse),
    ]
