# Generated by Django 4.2.30 on 2026-08-17 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_sanitize_provider_profile_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.BinaryField()),
                ('content_type', models.CharField(default='application/octet-stream', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stored_photo', to='accounts.providerprofile')),
            ],
        ),
    ]
