# Generated by Django 4.2.28 on 2026-02-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disputeevidence',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='disputes/evidence/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='disputeevidence',
            name='file_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
