# Generated by Django 4.2.28 on 2026-03-04 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_sanitize_provider_profile_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0005_booking_completion_confirmations'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderPayoutProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('SAUDI_BANK', 'Saudi Bank'), ('MPESA', 'M-Pesa'), ('USDT', 'USDT')], max_length=20)),
                ('bank_account_name', models.CharField(blank=True, max_length=160)),
                ('bank_name', models.CharField(blank=True, max_length=160)),
                ('saudi_iban', models.CharField(blank=True, max_length=34)),
                ('mpesa_full_name', models.CharField(blank=True, max_length=160)),
                ('mpesa_phone', models.CharField(blank=True, max_length=20)),
                ('usdt_network', models.CharField(blank=True, choices=[('TRC20', 'TRC20'), ('ERC20', 'ERC20')], max_length=10)),
                ('usdt_wallet_address', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout_profile', to='accounts.providerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PayoutLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=12)),
                ('payout_method', models.CharField(blank=True, choices=[('SAUDI_BANK', 'Saudi Bank'), ('MPESA', 'M-Pesa'), ('USDT', 'USDT')], max_length=20)),
                ('payout_details_snapshot', models.JSONField(blank=True, default=dict)),
                ('payout_date', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts_approved', to=settings.AUTH_USER_MODEL)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout_ledger', to='bookings.booking')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts_paid', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_ledger', to='accounts.providerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
