# Generated by Django 4.2.28 on 2026-02-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='currency',
            field=models.CharField(default='USD', max_length=8),
        ),
    ]
