# Generated by Django 4.2.28 on 2026-02-20 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
        ('accounts', '0001_initial'),
        ('marketplace', '0002_alter_service_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('UMRAH_BADAL', 'Umrah Badal'), ('ZIYARAH_GUIDE', 'Ziyarah Guide'), ('UMRAH_ASSISTANT', 'Umrah Assistant')], max_length=24)),
                ('city_scope', models.CharField(choices=[('MAKKAH', 'Makkah'), ('MADINAH', 'Madinah'), ('BOTH', 'Makkah & Madinah'), ('REMOTE', 'Remote')], max_length=16)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booked_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_availability_slot', to='bookings.booking')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='accounts.providerprofile')),
            ],
            options={
                'ordering': ['start_at'],
            },
        ),
    ]
