# Generated by Django 4.2.28 on 2026-02-23

from django.db import migrations, models


def force_usd_currency(apps, schema_editor):
    Service = apps.get_model("marketplace", "Service")
    Service.objects.exclude(currency="USD").update(currency="USD")


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0003_provideravailability"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="currency",
            field=models.CharField(choices=[("USD", "USD")], default="USD", max_length=8),
        ),
        migrations.RunPython(force_usd_currency, noop_reverse),
    ]
