# Generated by Django 4.2.28 on 2026-02-23 23:53

from django.db import migrations, models


def _resolve_city(value):
    text = str(value or "").strip().lower()
    if text in {"makkah", "mecca"}:
        return "MAKKAH"
    if text in {"madinah", "madina", "medina"}:
        return "MADINAH"
    return ""


def _resolve_provider_city(provider):
    city = _resolve_city(getattr(provider, "city", ""))
    if city:
        return city
    locations = getattr(provider, "base_locations", []) or []
    if isinstance(locations, (list, tuple)):
        for value in locations:
            resolved = _resolve_city(value)
            if resolved:
                return resolved
    return "MAKKAH"


def normalize_city_scopes(apps, schema_editor):
    Service = apps.get_model("marketplace", "Service")
    ProviderAvailability = apps.get_model("marketplace", "ProviderAvailability")

    for service in Service.objects.select_related("provider").all():
        if service.city_scope in {"MAKKAH", "MADINAH"}:
            continue
        service.city_scope = _resolve_provider_city(service.provider)
        service.save(update_fields=["city_scope"])

    for slot in ProviderAvailability.objects.select_related("provider").all():
        if slot.city_scope in {"MAKKAH", "MADINAH"}:
            continue
        slot.city_scope = _resolve_provider_city(slot.provider)
        slot.save(update_fields=["city_scope"])


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_force_service_currency_usd'),
    ]

    operations = [
        migrations.RunPython(normalize_city_scopes, noop_reverse),
        migrations.AlterField(
            model_name='provideravailability',
            name='city_scope',
            field=models.CharField(choices=[('MAKKAH', 'Makkah'), ('MADINAH', 'Madinah')], max_length=16),
        ),
        migrations.AlterField(
            model_name='service',
            name='city_scope',
            field=models.CharField(choices=[('MAKKAH', 'Makkah'), ('MADINAH', 'Madinah')], max_length=16),
        ),
    ]
