export const INTERNATIONAL_LANGUAGES = [
  { value: "Arabic", en: "Arabic", ar: "العربية" },
  { value: "English", en: "English", ar: "الإنجليزية" },
  { value: "Urdu", en: "Urdu", ar: "الأردية" },
  { value: "French", en: "French", ar: "الفرنسية" },
  { value: "Spanish", en: "Spanish", ar: "الإسبانية" },
  { value: "Turkish", en: "Turkish", ar: "التركية" },
  { value: "Indonesian", en: "Indonesian", ar: "الإندونيسية" },
  { value: "Malay", en: "Malay", ar: "الماليزية" },
  { value: "Hindi", en: "Hindi", ar: "الهندية" },
  { value: "Bengali", en: "Bengali", ar: "البنغالية" },
  { value: "Punjabi", en: "Punjabi", ar: "البنجابية" },
  { value: "Persian (Farsi)", en: "Persian (Farsi)", ar: "الفارسية" },
  { value: "Pashto", en: "Pashto", ar: "البشتوية" },
  { value: "Swahili", en: "Swahili", ar: "السواحلية" },
  { value: "Portuguese", en: "Portuguese", ar: "البرتغالية" },
  { value: "German", en: "German", ar: "الألمانية" },
  { value: "Italian", en: "Italian", ar: "الإيطالية" },
  { value: "Russian", en: "Russian", ar: "الروسية" },
  { value: "Chinese (Mandarin)", en: "Chinese (Mandarin)", ar: "الصينية (ماندرين)" },
  { value: "Chinese (Cantonese)", en: "Chinese (Cantonese)", ar: "الصينية (كانتونية)" },
  { value: "Japanese", en: "Japanese", ar: "اليابانية" },
  { value: "Korean", en: "Korean", ar: "الكورية" },
  { value: "Thai", en: "Thai", ar: "التايلاندية" },
  { value: "Filipino (Tagalog)", en: "Filipino (Tagalog)", ar: "الفلبينية (تاغالوغ)" },
  { value: "Tamil", en: "Tamil", ar: "التاميلية" },
  { value: "Telugu", en: "Telugu", ar: "التيلجو" },
  { value: "Malayalam", en: "Malayalam", ar: "المالايالامية" },
  { value: "Kannada", en: "Kannada", ar: "الكانادا" },
  { value: "Marathi", en: "Marathi", ar: "الماراثية" },
  { value: "Gujarati", en: "Gujarati", ar: "الغوجاراتية" },
  { value: "Nepali", en: "Nepali", ar: "النيبالية" },
  { value: "Somali", en: "Somali", ar: "الصومالية" },
  { value: "Amharic", en: "Amharic", ar: "الأمهرية" },
  { value: "Dutch", en: "Dutch", ar: "الهولندية" },
  { value: "Greek", en: "Greek", ar: "اليونانية" }
] as const;

